# Generated by Django 2.2 on 2019-04-14 22:25

from django.db import migrations, models
import shopping.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('cat', models.CharField(max_length=300)),
                ('price', models.FloatField()),
                ('image', models.ImageField(blank=True, null=True, upload_to=shopping.models.get_image_path)),
            ],
        ),
    ]
